// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AutomobileTn.CodedUITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UIAutomobileTnWindow UIAutomobileTnWindow
        {
            get
            {
                if ((this.mUIAutomobileTnWindow == null))
                {
                    this.mUIAutomobileTnWindow = new UIAutomobileTnWindow();
                }
                return this.mUIAutomobileTnWindow;
            }
        }
        
        public UIStartWindow UIStartWindow
        {
            get
            {
                if ((this.mUIStartWindow == null))
                {
                    this.mUIStartWindow = new UIStartWindow();
                }
                return this.mUIStartWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIAutomobileTnWindow mUIAutomobileTnWindow;
        
        private UIStartWindow mUIStartWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIAutomobileTnWindow : XamlWindow
    {
        
        public UIAutomobileTnWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "AutomobileTn";
            #endregion
        }
        
        #region Properties
        public UIMainHubHub UIMainHubHub
        {
            get
            {
                if ((this.mUIMainHubHub == null))
                {
                    this.mUIMainHubHub = new UIMainHubHub(this);
                }
                return this.mUIMainHubHub;
            }
        }
        
        public XamlButton UIConfirmAddButton
        {
            get
            {
                if ((this.mUIConfirmAddButton == null))
                {
                    this.mUIConfirmAddButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIConfirmAddButton.SearchProperties[XamlButton.PropertyNames.Name] = "Ajouter";
                    #endregion
                }
                return this.mUIConfirmAddButton;
            }
        }
        
        public XamlButton UIConfirmRemoveButton
        {
            get
            {
                if ((this.mUIConfirmRemoveButton == null))
                {
                    this.mUIConfirmRemoveButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIConfirmRemoveButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "button2";
                    #endregion
                }
                return this.mUIConfirmRemoveButton;
            }
        }
        
        public XamlText UILoadingDataText
        {
            get
            {
                if ((this.mUILoadingDataText == null))
                {
                    this.mUILoadingDataText = new XamlText(this);
                    #region Search Criteria
                    this.mUILoadingDataText.SearchProperties[XamlText.PropertyNames.AutomationId] = "textBlock";
                    #endregion
                }
                return this.mUILoadingDataText;
            }
        }
        #endregion
        
        #region Fields
        private UIMainHubHub mUIMainHubHub;
        
        private XamlButton mUIConfirmAddButton;
        
        private XamlButton mUIConfirmRemoveButton;
        
        private XamlText mUILoadingDataText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIMainHubHub : XamlHub
    {
        
        public UIMainHubHub(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlHub.PropertyNames.AutomationId] = "MainHub";
            #endregion
        }
        
        #region Properties
        public UITousHubSection UITousHubSection
        {
            get
            {
                if ((this.mUITousHubSection == null))
                {
                    this.mUITousHubSection = new UITousHubSection(this);
                }
                return this.mUITousHubSection;
            }
        }
        
        public UIFavorisHubSection UIFavorisHubSection
        {
            get
            {
                if ((this.mUIFavorisHubSection == null))
                {
                    this.mUIFavorisHubSection = new UIFavorisHubSection(this);
                }
                return this.mUIFavorisHubSection;
            }
        }
        
        public UIRechercheHubSection UIRechercheHubSection
        {
            get
            {
                if ((this.mUIRechercheHubSection == null))
                {
                    this.mUIRechercheHubSection = new UIRechercheHubSection(this);
                }
                return this.mUIRechercheHubSection;
            }
        }
        #endregion
        
        #region Fields
        private UITousHubSection mUITousHubSection;
        
        private UIFavorisHubSection mUIFavorisHubSection;
        
        private UIRechercheHubSection mUIRechercheHubSection;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UITousHubSection : XamlHubSection
    {
        
        public UITousHubSection(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlHubSection.PropertyNames.AutomationId] = "GroupedCarsSection";
            #endregion
        }
        
        #region Properties
        public UIGroupedCarsListViewList UIGroupedCarsListViewList
        {
            get
            {
                if ((this.mUIGroupedCarsListViewList == null))
                {
                    this.mUIGroupedCarsListViewList = new UIGroupedCarsListViewList(this);
                }
                return this.mUIGroupedCarsListViewList;
            }
        }
        #endregion
        
        #region Fields
        private UIGroupedCarsListViewList mUIGroupedCarsListViewList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIGroupedCarsListViewList : XamlList
    {
        
        public UIGroupedCarsListViewList(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "GroupedCarsListView";
            #endregion
        }
        
        #region Properties
        public UIAutomobileTnModelsGrListItem UIAutomobileTnModelsGrListItem
        {
            get
            {
                if ((this.mUIAutomobileTnModelsGrListItem == null))
                {
                    this.mUIAutomobileTnModelsGrListItem = new UIAutomobileTnModelsGrListItem(this);
                }
                return this.mUIAutomobileTnModelsGrListItem;
            }
        }
        
        public UIAutomobileTnModelsGrListItem2 UIAutomobileTnModelsGrListItem2
        {
            get
            {
                if ((this.mUIAutomobileTnModelsGrListItem2 == null))
                {
                    this.mUIAutomobileTnModelsGrListItem2 = new UIAutomobileTnModelsGrListItem2(this);
                }
                return this.mUIAutomobileTnModelsGrListItem2;
            }
        }
        #endregion
        
        #region Fields
        private UIAutomobileTnModelsGrListItem mUIAutomobileTnModelsGrListItem;
        
        private UIAutomobileTnModelsGrListItem2 mUIAutomobileTnModelsGrListItem2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIAutomobileTnModelsGrListItem : XamlListItem
    {
        
        public UIAutomobileTnModelsGrListItem(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlListItem.PropertyNames.Name] = "AutomobileTn.Models.GroupCars";
            #endregion
        }
        
        #region Properties
        public UIListViewList UIListViewList
        {
            get
            {
                if ((this.mUIListViewList == null))
                {
                    this.mUIListViewList = new UIListViewList(this);
                }
                return this.mUIListViewList;
            }
        }
        #endregion
        
        #region Fields
        private UIListViewList mUIListViewList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIListViewList : XamlList
    {
        
        public UIListViewList(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "listView";
            #endregion
        }
        
        #region Properties
        public XamlListItem AlfaRomeoGiuliettaCaListItem
        {
            get
            {
                if ((this.mAlfaRomeoGiuliettaCaListItem == null))
                {
                    this.mAlfaRomeoGiuliettaCaListItem = new XamlListItem(this);
                    #region Search Criteria
                    this.mAlfaRomeoGiuliettaCaListItem.SearchProperties[XamlListItem.PropertyNames.Name] = "AutomobileTn.Models.Car";
                    #endregion
                }
                return this.mAlfaRomeoGiuliettaCaListItem;
            }
        }
        
        public XamlListItem AlfaRomeoMitoCaListItem
        {
            get
            {
                if ((this.mAlfaRomeoMitoCaListItem == null))
                {
                    this.mAlfaRomeoMitoCaListItem = new XamlListItem(this);
                    #region Search Criteria
                    this.mAlfaRomeoMitoCaListItem.SearchProperties[XamlListItem.PropertyNames.Name] = "AutomobileTn.Models.Car";
                    this.mAlfaRomeoMitoCaListItem.SearchProperties[XamlListItem.PropertyNames.Instance] = "2";
                    #endregion
                }
                return this.mAlfaRomeoMitoCaListItem;
            }
        }
        #endregion
        
        #region Fields
        private XamlListItem mAlfaRomeoGiuliettaCaListItem;
        
        private XamlListItem mAlfaRomeoMitoCaListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIAutomobileTnModelsGrListItem2 : XamlListItem
    {
        
        public UIAutomobileTnModelsGrListItem2(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlListItem.PropertyNames.Name] = "AutomobileTn.Models.GroupCars";
            this.SearchProperties[XamlListItem.PropertyNames.Instance] = "5";
            #endregion
        }
        
        #region Properties
        public UIListViewList1 UIListViewList
        {
            get
            {
                if ((this.mUIListViewList == null))
                {
                    this.mUIListViewList = new UIListViewList1(this);
                }
                return this.mUIListViewList;
            }
        }
        #endregion
        
        #region Fields
        private UIListViewList1 mUIListViewList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIListViewList1 : XamlList
    {
        
        public UIListViewList1(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "listView";
            #endregion
        }
        
        #region Properties
        public XamlListItem CitroenC4PicassoCarListItem
        {
            get
            {
                if ((this.mCitroenC4PicassoCarListItem == null))
                {
                    this.mCitroenC4PicassoCarListItem = new XamlListItem(this);
                    #region Search Criteria
                    this.mCitroenC4PicassoCarListItem.SearchProperties[XamlListItem.PropertyNames.Name] = "AutomobileTn.Models.Car";
                    #endregion
                }
                return this.mCitroenC4PicassoCarListItem;
            }
        }
        #endregion
        
        #region Fields
        private XamlListItem mCitroenC4PicassoCarListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIFavorisHubSection : XamlHubSection
    {
        
        public UIFavorisHubSection(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlHubSection.PropertyNames.AutomationId] = "FavoritSection";
            #endregion
        }
        
        #region Properties
        public UIFavorisText UIFavorisText
        {
            get
            {
                if ((this.mUIFavorisText == null))
                {
                    this.mUIFavorisText = new UIFavorisText(this);
                }
                return this.mUIFavorisText;
            }
        }
        #endregion
        
        #region Fields
        private UIFavorisText mUIFavorisText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIFavorisText : XamlText
    {
        
        public UIFavorisText(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlText.PropertyNames.Name] = "Favoris";
            #endregion
        }
        
        #region Properties
        public XamlList UIFavoritItemList
        {
            get
            {
                if ((this.mUIFavoritItemList == null))
                {
                    this.mUIFavoritItemList = new XamlList(this);
                    #region Search Criteria
                    this.mUIFavoritItemList.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    #endregion
                }
                return this.mUIFavoritItemList;
            }
        }
        #endregion
        
        #region Fields
        private XamlList mUIFavoritItemList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIRechercheHubSection : XamlHubSection
    {
        
        public UIRechercheHubSection(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlHubSection.PropertyNames.AutomationId] = "SearchSection";
            #endregion
        }
        
        #region Properties
        public XamlHyperlink SearchByPriceHyperlink
        {
            get
            {
                if ((this.mSearchByPriceHyperlink == null))
                {
                    this.mSearchByPriceHyperlink = new XamlHyperlink(this);
                    #region Search Criteria
                    this.mSearchByPriceHyperlink.SearchProperties[XamlHyperlink.PropertyNames.Name] = "prix";
                    #endregion
                }
                return this.mSearchByPriceHyperlink;
            }
        }
        
        public XamlList SearchResultList
        {
            get
            {
                if ((this.mSearchResultList == null))
                {
                    this.mSearchResultList = new XamlList(this);
                    #region Search Criteria
                    this.mSearchResultList.SearchProperties[XamlList.PropertyNames.AutomationId] = "listView";
                    #endregion
                }
                return this.mSearchResultList;
            }
        }
        
        public XamlSlider SearchPriceSlider
        {
            get
            {
                if ((this.mSearchPriceSlider == null))
                {
                    this.mSearchPriceSlider = new XamlSlider(this);
                    #region Search Criteria
                    this.mSearchPriceSlider.SearchProperties[XamlSlider.PropertyNames.AutomationId] = "MainSearchSlider";
                    #endregion
                }
                return this.mSearchPriceSlider;
            }
        }
        
        public XamlHyperlink SearchModelHyperlink
        {
            get
            {
                if ((this.mSearchModelHyperlink == null))
                {
                    this.mSearchModelHyperlink = new XamlHyperlink(this);
                    #region Search Criteria
                    this.mSearchModelHyperlink.SearchProperties[XamlHyperlink.PropertyNames.Name] = "modèle";
                    #endregion
                }
                return this.mSearchModelHyperlink;
            }
        }
        
        public UIAutoSuggestBoxGroup UIAutoSuggestBoxGroup
        {
            get
            {
                if ((this.mUIAutoSuggestBoxGroup == null))
                {
                    this.mUIAutoSuggestBoxGroup = new UIAutoSuggestBoxGroup(this);
                }
                return this.mUIAutoSuggestBoxGroup;
            }
        }
        #endregion
        
        #region Fields
        private XamlHyperlink mSearchByPriceHyperlink;
        
        private XamlList mSearchResultList;
        
        private XamlSlider mSearchPriceSlider;
        
        private XamlHyperlink mSearchModelHyperlink;
        
        private UIAutoSuggestBoxGroup mUIAutoSuggestBoxGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIAutoSuggestBoxGroup : XamlControl
    {
        
        public UIAutoSuggestBoxGroup(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Group";
            this.SearchProperties["AutomationId"] = "autoSuggestBox";
            #endregion
        }
        
        #region Properties
        public XamlEdit ModelTextBoxEdit
        {
            get
            {
                if ((this.mModelTextBoxEdit == null))
                {
                    this.mModelTextBoxEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mModelTextBoxEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "TextBox";
                    #endregion
                }
                return this.mModelTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mModelTextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIStartWindow : UITestControl
    {
        
        public UIStartWindow()
        {
            #region Search Criteria
            this.TechnologyName = "UIA";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Window";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Start";
            this.SearchProperties["FrameworkId"] = "UIX";
            #endregion
        }
        
        #region Properties
        public UITestControl UIScrollerPane
        {
            get
            {
                if ((this.mUIScrollerPane == null))
                {
                    this.mUIScrollerPane = new UITestControl(this);
                    #region Search Criteria
                    this.mUIScrollerPane.TechnologyName = "UIA";
                    this.mUIScrollerPane.SearchProperties["FrameworkId"] = "UIX";
                    this.mUIScrollerPane.SearchProperties[UITestControl.PropertyNames.ControlType] = "Pane";
                    this.mUIScrollerPane.SearchProperties[UITestControl.PropertyNames.ClassName] = null;
                    this.mUIScrollerPane.SearchProperties["AutomationId"] = "Scroller";
                    #endregion
                }
                return this.mUIScrollerPane;
            }
        }
        #endregion
        
        #region Fields
        private UITestControl mUIScrollerPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItemWindow : UITestControl
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.TechnologyName = "UIA";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Window";
            this.SearchProperties["FrameworkId"] = "UIX";
            #endregion
        }
        
        #region Properties
        public UITestControl SearchAppBarButton
        {
            get
            {
                if ((this.mSearchAppBarButton == null))
                {
                    this.mSearchAppBarButton = new UITestControl(this);
                    #region Search Criteria
                    this.mSearchAppBarButton.TechnologyName = "UIA";
                    this.mSearchAppBarButton.SearchProperties["FrameworkId"] = "UIX";
                    this.mSearchAppBarButton.SearchProperties[UITestControl.PropertyNames.ControlType] = "Button";
                    this.mSearchAppBarButton.SearchProperties[UITestControl.PropertyNames.Name] = "rechercher";
                    #endregion
                }
                return this.mSearchAppBarButton;
            }
        }
        #endregion
        
        #region Fields
        private UITestControl mSearchAppBarButton;
        #endregion
    }
}
